version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
     
      # Use of docker buildx to create images in format arm64, arm/v7 and amd64, then push to a remote insecure registry.
      - run:
          name: Remove old installation
          command: |
            sudo service docker stop
            sudo apt remove docker-ce containerd.io docker docker-engine docker.io containerd runc
      - run:
          name: re install last version of docker
          command: |
            sudo apt-get update -y
            sudo apt-get -y install apt-transport-https ca-certificates curl gnupg-agent software-properties-common
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
            sudo apt-key fingerprint 0EBFCD88
            sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
            sudo apt-get install docker-ce docker-ce-cli containerd.io
      - run:
          name: Install buildx
          command: |
            BUILDX_BINARY_URL="https://github.com/docker/buildx/releases/download/v0.3.1/buildx-v0.3.1.linux-amd64"
            curl --output docker-buildx --silent --show-error --location --fail --retry 3 "$BUILDX_BINARY_URL"
            mkdir -p ~/.docker/cli-plugins
            export DOCKER_CLI_EXPERIMENTAL=enabled
            mv docker-buildx ~/.docker/cli-plugins/
            chmod a+x ~/.docker/cli-plugins/docker-buildx
            docker buildx install
            docker run --rm --privileged docker/binfmt:a7996909642ee92942dcd6cff44b9b95f08dad64
            # Display the installed contexts (arm64, etc)
            docker buildx ls
            sudo ls -al /proc/sys/fs/binfmt_misc
            sudo cat /proc/sys/fs/binfmt_misc/qemu-aarch64
            sudo cat /proc/sys/fs/binfmt_misc/qemu-arm           
      - run:
         name: Configuring docker daemon to use insecure registries
         command: |
           json=`mktemp`
           # Put your own remote insecure registry in place of "pierdobauce.ddns.net:5000" 
           echo '{ "insecure-registries": [ "pierdobauce.ddns.net:5000" ] }' > ${json}
           sudo mv ${json} /etc/docker/daemon.json
           sudo service docker restart
           echo "Configured Docker daemon with insecure-registry"           
      - run:
          name: Use buildx
          command: |
             docker buildx create --name mybuilder --config buildxconfigfile
             docker buildx use mybuilder
             docker buildx inspect --bootstrap         
      - run:
         name: Connecting the remote insecure registry
         command: |
           # Put your user and password. Better: use global variables for this.
           docker login -u pierdo -p pierd0 pierdobauce.ddns.net:5000
      - run:
          name: Create and push image
          command: |
             # Choose the platforms. Here I push to my registry.
             docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -f Dockerfile_extract --push -t pierdobauce.ddns.net:5000/extract .


            
